{% set num_splashes = cookiecutter.num_splashes|int %}
{% set splash_slots = cookiecutter.splash_slots|int %}
{% set max_timeout = cookiecutter.max_timeout|int %}
{% set maxrss = cookiecutter.maxrss_mb | int %}
{% set mem_limit = "%dm" | format(maxrss * 1.4) %}
{% set memswap_limit = "%dm" | format(maxrss * 1.8) %}
{% set verbosity = cookiecutter.splash_verbosity %}

version: '2'

services:
    haproxy:
        image: haproxy:1.7
        ports:
            # stats
            - "8036:8036"

            # splash
            - "8050:8050"
        links:
            {%- for i in range(num_splashes) %}
            - splash{{i}}
            {%- endfor %}
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

    {%- for i in range(num_splashes) %}

    splash{{i}}:
        image: scrapinghub/splash:{{ cookiecutter.splash_version }}
        command: --max-timeout {{ max_timeout }} --slots {{ splash_slots }} --maxrss {{ maxrss }} --verbosity {{ verbosity }}
        expose:
            - 8050
        networks:
          aq-lb-splashes:
            aliases:
              - splash{{i}}.simplelegal.com    
        mem_limit: {{ mem_limit }}
        memswap_limit: {{ memswap_limit }}
        restart: always

    {%- endfor %}

networks:
  aq-splash:
  aq-lb-splashes:
